### ISSUE TITLE
There is already an open DataReader associated with this Connection which must be closed first.

### ISSUE THREAD

**Issue by karthikkavin** [exceptionnotfound/AspNetCoreDapperAsyncDemo#2]
Hi, I used the c# Asp.net core 2.2 MySQL database with multiple threads running at the same time on my back end service. 
When this two threads running on the same time to call db connection I got the below error:

> MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.LoadServerProperties(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
>

my db connection code is below:
`
       private IDbConnection _DBConnection = null;
        public IDbConnection GetDatabaseConnection
        {
            get
            {
                if (_DBConnection == null)
                {
                    _DBConnection = new MySqlConnection("connection string");
                }
                if (_DBConnection.State != ConnectionState.Open)
                {
                    _DBConnection.Open();
                }
                return _DBConnection;
            }
        }

added services layer code:

> services.AddScoped<IEmpDatabase,  EmpDatabase>();

using (var connection = _databaseImpl.GetDatabaseConnection)
{	
	var qryResult = await connection.QueryAsync<MyEmpLogEntity>("Select * from employeelog");
	return  qryResult.ToList();
}
`
How to fix this issue?

**Comment by exceptionnotfound** [comment]
Apologies, but I am not a help desk.  You might have a better time getting your questions answered on StackOverflow; I have no experience with MySQL.

**Comment by karthikkavin** [comment]
I fixed this issue to change below code for configure service 
services.AddScoped<IEmpDatabase, EmpDatabase>(); 
to 
services.AddTransient<IEmpDatabase, EmpDatabase>();
